export const PROFILES_RESET = "PROFILES_RESET";
export const PROFILES_ADD = "PROFILES_ADD";

export const BOARD_RESET = "BOARD_RESET";
export const BOARD_SET_TILES = "BOARD_SET_TILES";
export const BOARD_SELECT_TILE = "BOARD_SELECT_TILE";
export const BOARD_CLEAR_SELECTIONS = "BOARD_CLEAR_SELECTIONS";
export const BOARD_ADD_DISCOVERED = "BOARD_ADD_DISCOVERED";

